default_agent: mahen_tech_agent
agents:
  mahen_tech_agent:
    name: mahen_tech_agent
    entrypoint: /Users/mahen/learnings/AI/ai-agent/agent-aws/multi-agent/tech_agent/tech_agent.py
    platform: linux/arm64
    container_runtime: none
    aws:
      execution_role: arn:aws:iam::471727841202:role/agentcore-tech_agent-role
      execution_role_auto_create: false
      account: '471727841202'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: mahen_tech_agent-bgFBX1GVzl
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:471727841202:runtime/mahen_tech_agent-bgFBX1GVzl
      agent_session_id: b728a20f-f408-4525-86d4-dab6d879aba8
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
